---
title: "PS 1"
author: "Elmer S. Poliquit"
date: "2024-01-31"
output: pdf_document
header-includes: |
  \usepackage{graphicx}
  \graphicspath{ {figures/} }
  \usepackage{array}
  \usepackage{amsmath}
  \usepackage{xcolor}
  \usepackage{bigints}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Problem Set 1

1. Prove that $lim_{x\rightarrow -1}{2x}+1=-1.$

Note: For any given $\epsilon > 0$, there exists a $\delta > 0$ such that $|f (x) - f (x_0)| < \epsilon$ whenever $|x - x_0| < \delta$.

Draft:

$$|2x+1 - (-1)| < \epsilon$$
$$|2x+2| < \epsilon$$
$$|2||x-(-1)|<\epsilon$$
$$ |x-(-1)| < \frac{\epsilon}{|2|} $$
$$ \delta \leq \frac{\epsilon}{2} $$ 

2. Determine all the numbers $c$ which satisfy the conclusions of the Mean Value Theorem for the following function and graph using $\mathrm{R}$ with the point/s identified. $f(x)=x^3-4 x^2-2 x-5$ on $[-10,10]$.

3. Find the point $c$ that satisfies the mean value theorem for integrals on the interval $[-1,1]$. The function is $f(x)=2 e^x$.

4. Consider the function $f(x)=\cos (x / 2)$.
a Find the fourth Taylor polynomial for $f$ at $x=\pi$.
b Use the fourth Taylor polynomial to approximate $\cos (\pi / 2)$.
c Use the fourth Taylor polynomial to bound the error.

5. If $f l(x)$ is the machine approximated number of a real number $x$ and $\epsilon$ is the corresponding relative error, then show that $f l(x)=(1-\epsilon) x$.

6. For the following numbers $x$ and their corresponding approximations $x_A$, find the number of significant digits in $x_A$ with respect to $x$ and find the relative error.
a. $x=451.01, x_A=451.023$
b. $x=-0.04518, x_A=-0.045113$
c. $x=23.4604, x_A=23.4213$

Note:

Relative error

$E(x_A) = x - x_A$
$E_r(x_A) = \frac{E(x_A)}{x}$

Significant Digits

$\left|x-x_A\right| \leq \frac{1}{2} \beta^{s-r+1}$

Draft:

a. $x=451.01, x_A=451.023$

Relative Error:

$E(x_a) = 451.01 - 451.023 = -0.013$

$E_r(x_a) = \frac{-0.013}{451.01} = -0.00002882419$

Significant Digits:

$|x-x_A| = 0.013 < 0.5 = \frac{1}{2}\times10^0$. But $10^2 < 451.01$. Therefore $s = 2$ and $r = 6$

$0.013 \leq \frac{1}{2} \beta^{2-6+1} = \frac{1}{2} \times 10^{-3} = 0.0005$

b. $x=-0.04518, x_A=-0.045113$

Relative Error:

$E(x_a) = -0.04518 - (-0.045113) = -0.000067$

$E_r(x_a) = \frac{-0.000067}{-0.04518} = 0.00148295706$

Significant Digits:

$|x-x_A| = 0.000067 < 0.0005 = \frac{1}{2}\times10^{-3}$. But $10^{-2} < 0.04518$. Therefore $s = -2$ and $r = 5$

$0.000067 \leq \frac{1}{2} \beta^{-2-5+1} = \frac{1}{2} \times 10^{-6} = 0.0000005$

c. $x=23.4604, x_A=23.4213$

Relative Error:

$E(x_a) = 23.4604 - 23.4213 = 0.0391$

$E_r(x_a) = \frac{0.0391}{23.4604} = 0.00166663824$

Significant Digits:

$|x-x_A| = 0.0391 < 0.5 = \frac{1}{2}\times10^{0}$. But $10^{1} < 23.4213$. Therefore $s = 1$ and $r = 6$

$0.0391 \leq \frac{1}{2} \beta^{1-6+1} = \frac{1}{2} \times 10^{-4} = 0.00005$

7. Find the condition number for the following functions
a. $f(x)=2 x^2$
b. $f(x)=2 \pi^x$
c. $f(x)=2 b^x$

Note: The condition number of a function $f$ at a point $x = c$ is given by
$$\left|\frac{f^{\prime}(c)}{f(c)} c\right|$$

Draft:

a.

$f(x)=2 x^2$, for all $x \epsilon R$

Then $f'(x)=4 x$, so that

$$\left|\frac{f^{\prime}(x)}{f(x)} x\right| = \left|\frac{2 x^2}{4 x} x\right| = \left|\frac{x^2}{2}\right|$$

b.

$f(x)=2 \pi^x$, for all $x \epsilon R$

Then $f'(x)=2 \pi^{x}\ln(\pi)$, so that

$$\left|\frac{f^{\prime}(x)}{f(x)} x\right| = \left|\frac{2 \pi^x}{2 \pi^{x}\ln(\pi)} x\right| = \left|\frac{x}{\ln(\pi)}\right|$$

c.

$f(x)=2 b^x$, for all $x \epsilon R$

Then $f'(x)=2 b^x\ln(b)$, so that

$$\left|\frac{f^{\prime}(x)}{f(x)} x\right| = \left|\frac{2 b^x}{2 b^{x}\ln(b)} x\right| = \left|\frac{x}{\ln(b)}\right|$$

8. Determine if the following series converges or diverges. If it converges determine its sum.
$$ \sum_{n=1}^{\infty} \frac{1}{2^n} $$